name: Docker Image CI (Manually)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{ secrets.SSH_ARM64_RUNNER }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY_ARM64_RUNNER }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ${{ secrets.AMD64_RUNNER_ENDPOINT }}
          append: |
            - endpoint: ${{ secrets.ARM64_RUNNER_ENDPOINT }}
              platforms: linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout Joplin from NavyStack
        uses: actions/checkout@v4
        with:
          repository: NavyStack/joplin
          path: joplin
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./joplin/
          file: ./joplin/Dockerfile.server
          push: true
          tags: |
            navystack/joplin-server:latest
            navystack/joplin-server:2
            navystack/joplin-server:2.14
            navystack/joplin-server:2.14.1
          platforms: linux/amd64,linux/arm64
